# Generated by Django 4.0.5 on 2022-06-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_band_active_band_biography_band_genre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('sold', models.BooleanField(default=False)),
                ('year', models.IntegerField()),
                ('type', models.CharField(choices=[('CL', 'Clothing'), ('PO', 'Posters'), ('MI', 'Miscellaneous')], max_length=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Object',
        ),
    ]
