# Generated by Django 4.0.5 on 2022-06-21 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_remove_band_like_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('tel', models.IntegerField(default=0)),
                ('ville', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomProduit', models.CharField(choices=[('FR', 'Fourree'), ('CH', 'Chocotom'), ('SM', 'Smile'), ('SA', 'Saida'), ('BI', 'Binto')], max_length=100)),
                ('image', models.ImageField(upload_to='produits')),
                ('prixAchat', models.FloatField(default=0)),
                ('prixVente', models.FloatField(default=0)),
                ('quantiteEnStock', models.IntegerField(default=0)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.fournisseur')),
            ],
        ),
        migrations.RemoveField(
            model_name='listing',
            name='band',
        ),
        migrations.DeleteModel(
            name='Band',
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
