# Generated by Django 4.0.5 on 2022-06-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_alter_produit_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='gerant',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
