# Generated by Django 4.0.5 on 2022-06-23 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0015_alter_produit_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produit',
            options={'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
        migrations.RemoveField(
            model_name='produit',
            name='prixAchat',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='prixVente',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='quantiteEnStock',
        ),
        migrations.AddField(
            model_name='produit',
            name='prix',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='tel',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.produit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('frais_de_livraison', models.IntegerField(default=7, verbose_name='Frais De Livraison')),
                ('item', models.ManyToManyField(to='listings.orderitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
