# Generated by Django 4.0.5 on 2022-06-24 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0024_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
