# Generated by Django 4.0.5 on 2022-06-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0027_remove_cart_ordered_remove_cart_ordered_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_orders',
            field=models.FloatField(default=0.0),
        ),
    ]
